USE [master]
GO

/****** Object:  Database [CompressionSetting]    Script Date: 02.11.2018 16:12:45 ******/
CREATE DATABASE [CompressionSetting]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CompressionSetting', FILENAME = N'D:\Data\CompressionSetting.mdf' , SIZE = 401408KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CompressionSetting_log', FILENAME = N'F:\LOG_SQL\CompressionSetting_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CompressionSetting] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CompressionSetting].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CompressionSetting] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CompressionSetting] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CompressionSetting] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CompressionSetting] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CompressionSetting] SET ARITHABORT OFF 
GO

ALTER DATABASE [CompressionSetting] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CompressionSetting] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CompressionSetting] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CompressionSetting] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CompressionSetting] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CompressionSetting] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CompressionSetting] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CompressionSetting] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CompressionSetting] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CompressionSetting] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CompressionSetting] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CompressionSetting] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CompressionSetting] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CompressionSetting] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CompressionSetting] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CompressionSetting] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CompressionSetting] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CompressionSetting] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CompressionSetting] SET  MULTI_USER 
GO

ALTER DATABASE [CompressionSetting] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CompressionSetting] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CompressionSetting] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CompressionSetting] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CompressionSetting] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CompressionSetting] SET QUERY_STORE = OFF
GO

USE [CompressionSetting]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CompressionSetting] SET  READ_WRITE 
GO


