USE [master]
GO

/****** Object:  Database [ForReglament]    Script Date: 25.06.2019 10:12:40 ******/
CREATE DATABASE [ForReglament]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ForReglament', FILENAME = N'D:\Data\ForReglament.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ForReglament_log', FILENAME = N'F:\LOG_SQL\ForReglament_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ForReglament] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ForReglament].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ForReglament] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ForReglament] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ForReglament] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ForReglament] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ForReglament] SET ARITHABORT OFF 
GO

ALTER DATABASE [ForReglament] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ForReglament] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ForReglament] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ForReglament] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ForReglament] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ForReglament] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ForReglament] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ForReglament] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ForReglament] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ForReglament] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ForReglament] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ForReglament] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ForReglament] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ForReglament] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ForReglament] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ForReglament] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ForReglament] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ForReglament] SET RECOVERY FULL 
GO

ALTER DATABASE [ForReglament] SET  MULTI_USER 
GO

ALTER DATABASE [ForReglament] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ForReglament] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ForReglament] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ForReglament] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ForReglament] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ForReglament] SET QUERY_STORE = OFF
GO

USE [ForReglament]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [ForReglament] SET  READ_WRITE 
GO


